### ISSUE TITLE
yogi build fails to build relative css-imagepaths into the right absolute path

### ISSUE THREAD

**Issue by ItsAsbreuk** [yui/yogi#93]
Having the file

gallery-somemodule/assets/gallery-somemodule/skins/gallery-somemodule-core.css

and in there the css-rule:

``` css
.withimage {
    background-image: url('myimage.png');
}
```

yogi build should translate the relative uri into the current gallery-version-build+path.
However, it leaves the uri just as it is, resulting the browser to load http://yui.yahooapis.com/myimage.png

Now all modules with relative css-images don't show their images.

Best Regards,
Marco.
